name: dotless_i
version: 0.1.0
author: Ahmet A. Akın <ahmetaa@gmail.com>
description: Turkish String upper-lower case converter and comparator
homepage: https://github.com/ahmetaa/dotless_i
dev_dependencies:
  unittest: '>=0.5.0'
