name: dotless_i
version: 0.1.5
authors:
- Ahmet A. Akın <ahmetaa@gmail.com>
- Mehmet D. Akın <mdakin@gmail.com>
description: Turkish String upper-lower case converter and comparator
homepage: https://github.com/ahmetaa/dotless_i
environment:
  sdk: '>=0.8.10+6 <2.0.0'
dev_dependencies:
  unittest: '>=0.9.0 <0.10.0'
